#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

. /minios.conf || exit 1



SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

pkg update

# install packages
if [ -f $SCRIPT_DIR/package.list ]; then
    install_packages
fi


# Install RustDesk 1.2.3-1

pkg update
wget -q --show-progress "https://github.com/rustdesk/rustdesk/releases/download/1.2.3-1/rustdesk-1.2.3-1-x86_64.deb"
pkg install ./rustdesk-1.2.3-1-x86_64.deb -y
rm -f rustdesk-1.2.3-1-x86_64.deb
