#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"


# Download and Install DBeaver Community 24.0.1

wget -q --show-progress https://github.com/FershoUno/packages/releases/download/v1.0.0/dbeaver-ce_24.0.1_amd64.deb
pkg install ./dbeaver-ce_24.0.1_amd64.deb -y
rm -f dbeaver-ce_24.0.1_amd64.deb
