#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

pkg update

# install packages
if [ -f $SCRIPT_DIR/package.list ]; then
    install_packages
fi


# Download Lazarus IDE
# fpc-laz
wget -q --show-progress "https://github.com/FershoUno/packages/releases/download/v1.0.0/fpc-laz_3.2.2-210709_amd64.deb"

# fpc-src
wget -q --show-progress "https://github.com/FershoUno/packages/releases/download/v1.0.0/fpc-src_3.2.2-210709_amd64.deb"

# lazarus-project
wget -q --show-progress "https://github.com/FershoUno/packages/releases/download/v1.0.0/lazarus-project_3.0.0-0_amd64.deb"

# Installing Lazarus IDE
pkg update
pkg install ./fpc-laz_3.2.2-210709_amd64.deb -y
pkg install ./fpc-src_3.2.2-210709_amd64.deb -y
pkg install ./lazarus-project_3.0.0-0_amd64.deb -y

# remove downloaded packages
rm -f fpc-laz_3.2.2-210709_amd64.deb fpc-src_3.2.2-210709_amd64.deb lazarus-project_3.0.0-0_amd64.deb 

# Download Pseint
wget -q --show-progress "https://github.com/FershoUno/packages/releases/download/v1.0.0/pseint-l64-20240122_amd64.deb"
pkg install ./pseint-l64-20240122_amd64.deb -y

# remove pseint
rm -f pseint-l64-20240122_amd64.deb

# Download Icon Gambas3  (REMOVED)
#wget -q --show-progress "https://github.com/FershoUno/packages/releases/download/v1.0.0/gambas3-ide-icon_1.0.0_all.deb"
#pkg install ./gambas3-ide-icon_1.0.0_all.deb -y
#rm -f gambas3-ide-icon_1.0.0_all.deb

# Download and Install 
wget -q --show-progress  "https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb" -O packages-microsoft-prod.deb
pkg install ./packages-microsoft-prod.deb
rm -f packages-microsoft-prod.deb

# Installation SDK-8.0 y ASP.NET Core from repository
pkg update
pkg install dotnet-sdk-8.0 aspnetcore-runtime-8.0 -y



