#!/bin/bash

set -e          # exit on error
set -o pipefail # exit on pipeline error
set -u          # treat unset variable as error

. /minioslib || exit 1

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

pkg update

# install packages
if [ -f $SCRIPT_DIR/package.list ]; then
    install_packages
fi


# Install Apache NetBeans 21.1

wget -q --show-progress https://dlcdn.apache.org/netbeans/netbeans-installers/21/apache-netbeans_21-1_all.deb

pkg install ./apache-netbeans_21-1_all.deb -y

rm -f apache-netbeans_21-1_all.deb
